import { createNationState } from "./state/nationState.js";
import { createPublicOpinion } from "./state/publicOpinion.js";
import { createEconomyState } from "./state/economyState.js";

import { createCrisisSystem } from "./systems/crisisSystem.js";
import { createElectionSystem } from "./systems/electionSystem.js";
import { createNewsSystem } from "./systems/newsSystem.js";
import { createPolicySystem } from "./systems/policySystem.js";

import { mountDashboard } from "./ui/dashboard.js";
import { mountNewsFeed } from "./ui/newsFeed.js";
import { mountDepartmentView } from "./ui/departmentView.js";
import { mountDecisionModal } from "./ui/decisionModal.js";
import { mountMapView } from "./ui/mapView.js";

async function loadJson(path){
  const res = await fetch(path);
  if(!res.ok) throw new Error(`Failed to load ${path}`);
  return await res.json();
}

function clamp(n, lo, hi){ return Math.max(lo, Math.min(hi, n)); }

(async function bootstrap(){
  const [crises, newsTemplates, departments, policies] = await Promise.all([
    loadJson("./data/crises.json"),
    loadJson("./data/newsTemplates.json"),
    loadJson("./data/departments.json"),
    loadJson("./data/policies.json"),
  ]);

  const nation = createNationState();
  const opinion = createPublicOpinion({ initialApproval: 55 });
  const economy = createEconomyState();

  const news = createNewsSystem({ templates: newsTemplates });
  const crisisSystem = createCrisisSystem({ crisisDefs: crises });
  const policySystem = createPolicySystem({ policies });
  const election = createElectionSystem();

  // UI Mount
  const dashboard = mountDashboard();
  const newsFeed = mountNewsFeed(document.getElementById("newsFeed"));
  const deptView = mountDepartmentView(document.getElementById("departmentView"), departments);
  const mapView = mountMapView(document.getElementById("mapView"));
  const decisionModal = mountDecisionModal({
    onChoice: (payload) => handleDecision(payload),
  });

  // Tabs
  const tabsEl = document.getElementById("tabs");
  tabsEl.addEventListener("click", (e) => {
    const btn = e.target.closest("[data-tab]");
    if(!btn) return;
    const tab = btn.dataset.tab;
    [...tabsEl.querySelectorAll(".tab")].forEach(b => b.classList.toggle("tab--active", b.dataset.tab === tab));
    document.getElementById("tabBrief").classList.toggle("tabPane--active", tab === "brief");
    document.getElementById("tabDepts").classList.toggle("tabPane--active", tab === "depts");
    document.getElementById("tabInbox").classList.toggle("tabPane--active", tab === "inbox");
    document.getElementById("tabHistory").classList.toggle("tabPane--active", tab === "history");
  });

  // Game Over UI
  const goBackdrop = document.getElementById("gameOverBackdrop");
  const goModal = document.getElementById("gameOverModal");
  const goBody = document.getElementById("goBody");
  document.getElementById("goRestart").addEventListener("click", () => window.location.reload());

  // Advance buttons
  document.getElementById("btnAdvance1").addEventListener("click", async () => advanceYears(1));
  document.getElementById("btnAdvance5").addEventListener("click", async () => advanceYears(5));

  // Initial seed content
  news.pushImmediate({
    title: "建国宣言、国民は期待と不安の入り混じった空気",
    body: "国家の黎明期。制度もインフラも未成熟だが、意思決定の一つひとつが将来を決める。危機は必ず起きる。",
    tags: ["国内", "政治"],
    source: "国営放送",
    severity: "info",
    year: nation.year
  });

  crisisSystem.ensureBaseline(nation);
  renderAll();

  // ===== Core Loop =====

  async function advanceYears(n){
    // stop if modal open
    if(decisionModal.isOpen()) return;
    if(goModal.classList.contains("hidden") === false) return;

    for(let i=0; i<n; i++){
      // 1) advance time
      nation.advanceYear();

      // 2) phase updates
      nation.updatePhase();

      // 3) systems tick
      const tickCtx = { nation, opinion, economy };

      // crisis: maintain 2-4 latent crises, progress them, and produce triggers
      const crisisEvents = crisisSystem.tick(tickCtx);

      // policy: occasionally propose non-crisis policy (still tied to narrative)
      const policyEvents = policySystem.tick(tickCtx);

      // economy responds to hidden structural state + shocks
      economy.tick({
        year: nation.year,
        phase: nation.phase,
        structural: nation.hidden.structural,
        shocks: nation.hidden.shocks,
      });

      // public opinion responds to pressure + recent mishandling + narrative
      opinion.tick({
        year: nation.year,
        phase: nation.phase,
        pressures: nation.hidden.pressures,
        shocks: nation.hidden.shocks,
        comms: nation.hidden.comms,
      });

      // 4) push delayed news
      news.flushDue(nation.year);

      // 5) add new news generated by systems (some delayed)
      for(const ev of crisisEvents.news){
        news.push(ev, nation.year);
      }
      for(const ev of policyEvents.news){
        news.push(ev, nation.year);
      }

      // 6) department inbox notifications (text-only)
      deptView.addInboxItems([
        ...crisisEvents.notifications,
        ...policyEvents.notifications,
      ]);

      // 7) history log
      nation.history.push({
        year: nation.year,
        title: `建国${nation.year}年の記録`,
        body: nation.historyDraft.splice(0).join("\n"),
      });

      // 8) elections
      if(election.isElectionYear(nation)){
        const result = election.resolve({ approval: opinion.approval, nation });
        if(result.lose){
          // game over
          const epilogue = election.buildEpilogue({ nation, opinion, economy, news });
          goBody.innerHTML = `
            <div class="card">
              <div class="card__title">歴史の評価</div>
              <div class="card__text">${escapeHtml(epilogue).replaceAll("\n","<br/>")}</div>
            </div>
          `;
          goBackdrop.classList.remove("hidden");
          goModal.classList.remove("hidden");
          renderAll();
          return;
        } else {
          news.pushImmediate({
            title: "選挙、与党が辛勝。国は当面の継続を選ぶ",
            body: "勝利は免罪符ではない。危機の積み残しが、次の任期に影を落とす。",
            tags: ["政治"],
            source: "全国紙",
            severity: opinion.approval < 30 ? "warn" : "info",
            year: nation.year
          });
        }
      }

      // 9) decision gates: if there is a required decision, open modal and stop further years
      const required = crisisSystem.popRequiredDecision() ?? policySystem.popRequiredDecision();
      if(required){
        decisionModal.open(required);
        nation.historyDraft.push(`決断：${required.title}`);
        renderAll();
        return;
      }

      renderAll();
    }
  }

  function handleDecision(payload){
    // payload = { kind, id, choiceId, ... }
    const ctx = { nation, opinion, economy };
    if(payload.kind === "crisis"){
      crisisSystem.applyDecision(payload, ctx, news, deptView);
    } else if(payload.kind === "policy"){
      policySystem.applyDecision(payload, ctx, news, deptView);
    }
    renderAll();
  }

  function renderAll(){
    // topbar
    dashboard.setYear(nation.year);
    dashboard.setApproval(opinion.approval);
    dashboard.setGdpTier(economy.gdpTier);
    dashboard.setPhase(nation.phaseLabel);
    dashboard.setNextElection(election.nextElectionYear(nation));

    // map
    mapView.render({ nation, opinion, economy });

    // brief
    document.getElementById("briefText").textContent = buildBrief(nation, opinion, economy);
    document.getElementById("hintText").textContent = buildHint(nation, opinion, economy);

    // news
    newsFeed.render(news.getRecent(30));

    // dept report
    deptView.renderReport({
      nation,
      opinion,
      economy,
      hidden: nation.hidden,
      year: nation.year,
    });

    // inbox
    renderInbox(deptView.getInbox());

    // history
    renderHistory(nation.history.slice(-30));
  }

  function renderInbox(items){
    const el = document.getElementById("inboxView");
    el.innerHTML = "";
    if(items.length === 0){
      el.innerHTML = `<div class="card"><div class="card__text">通知はありません。</div></div>`;
      return;
    }
    for(const it of items.slice().reverse()){
      const div = document.createElement("div");
      div.className = "inboxItem";
      div.innerHTML = `
        <div class="inboxItem__title">${escapeHtml(it.title)}</div>
        <div class="inboxItem__body">${escapeHtml(it.body)}</div>
        <div class="inboxItem__meta">建国${it.year}年 / ${escapeHtml(it.from)}</div>
      `;
      el.appendChild(div);
    }
  }

  function renderHistory(items){
    const el = document.getElementById("historyView");
    el.innerHTML = "";
    if(items.length === 0){
      el.innerHTML = `<div class="card"><div class="card__text">年表はまだありません。</div></div>`;
      return;
    }
    for(const it of items.slice().reverse()){
      const div = document.createElement("div");
      div.className = "historyItem";
      div.innerHTML = `
        <div class="historyItem__title">${escapeHtml(it.title)}</div>
        <div class="historyItem__body">${escapeHtml(it.body)}</div>
        <div class="historyItem__meta">建国${it.year}年</div>
      `;
      el.appendChild(div);
    }
  }

  function buildBrief(nation, opinion, economy){
    const danger = opinion.approval <= 20 ? "政権崩壊が視野に入っている。" :
                   opinion.approval <= 30 ? "政権は危険水域。小さな失点が致命傷になる。" :
                   opinion.approval <= 45 ? "国民は不安定。説明不足は不信を増幅する。" :
                   "当面は持ちこたえているが、慢心は危険。";
    const gdp = `GDPは「${economy.gdpTier}」。成熟期ほど伸びにくい。`;
    const phase = `国家フェーズは「${nation.phaseLabel}」。年月が進むほど、修復は高コストになる。`;
    return `${phase}\n${gdp}\n${danger}`;
  }

  function buildHint(nation, opinion, economy){
    // “正解助言”は禁止。状況の読み方だけを示す。
    const hints = [];
    hints.push("ニュースの小さな兆候が、数年後の爆発を予告している場合がある。");
    hints.push("部局報告は偏る。楽観・保身・危機煽りを見抜け。");
    if(opinion.approval <= 28) hints.push("支持率が低い時期は、内容以上に“姿勢”が問われる。");
    if(economy.gdpTier === "停滞") hints.push("停滞期は、成長よりも破綻回避が重要になる。");
    if(nation.phase === "mature") hints.push("成熟期は『何も起きない』の維持が最大の勝利条件になる。");
    return hints.join("\n");
  }

  function escapeHtml(s){
    return String(s)
      .replaceAll("&","&amp;")
      .replaceAll("<","&lt;")
      .replaceAll(">","&gt;")
      .replaceAll('"',"&quot;")
      .replaceAll("'","&#039;");
  }
})().catch(err => {
  console.error(err);
  alert("起動に失敗しました。コンソールを確認してください。\n" + err.message);
});
